// src/pages/ObjectWall.vue
<template>
  <div class="max-w-5xl mx-auto px-4 py-8">
    <h1 class="text-3xl font-bold mb-2">🏛️ {{ p.heading }}</h1>
    <p class="text-slate-400 mb-8">{{ p.description }}</p>

    <!-- Item Grid (model-viewer preview cards) -->
    <div class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4">
      <button
        v-for="item in items"
        :key="item.id"
        @click="openViewer(item)"
        class="group rounded-2xl bg-slate-800/60 border border-slate-700 overflow-hidden hover:border-indigo-500/50 hover:scale-[1.03] transition-all duration-300 text-left"
      >
        <!-- 3D Model Preview (lightweight, no interaction) -->
        <div class="h-36 sm:h-44 bg-slate-900 relative">
          <model-viewer
            :src="item.model_url"
            :alt="item.name"
            interaction-prompt="none"
            shadow-intensity="0.5"
            environment-image="neutral"
            exposure="0.8"
            camera-orbit="0deg 65deg 105%"
            min-camera-orbit="-80deg auto auto"
            max-camera-orbit="80deg auto auto"
            disable-zoom
            style="width: 100%; height: 100%; pointer-events: none;"
          ></model-viewer>
        </div>
        <!-- Name -->
        <div class="p-3 text-center">
          <h3 class="text-sm font-semibold text-white group-hover:text-indigo-400 transition-colors">
            {{ item.name }}
          </h3>
          <p class="text-xs text-slate-500 mt-1">點擊查看</p>
        </div>
      </button>
    </div>

    <!-- Fullscreen Viewer (opens directly) -->
    <Teleport to="body">
      <Transition name="modal">
        <div v-if="activeItem" class="fixed inset-0 z-[200] bg-black flex flex-col">
          <!-- Top Bar -->
          <div class="flex items-center justify-between px-4 py-3 bg-slate-900/90 backdrop-blur-sm z-10">
            <h3 class="text-white font-bold text-lg">{{ activeItem.name }}</h3>
            <div class="flex gap-2">
              <!-- Toggle UI controls -->
              <button
                @click="showControls = !showControls"
                :class="[
                  'w-9 h-9 rounded-full flex items-center justify-center text-white text-sm transition-colors',
                  showControls ? 'bg-indigo-600 hover:bg-indigo-500' : 'bg-slate-700/80 hover:bg-slate-600'
                ]"
                title="顯示/隱藏控制按鈕"
              >
                🔍
              </button>
              <button
                @click="closeViewer"
                class="w-9 h-9 rounded-full bg-slate-700 hover:bg-slate-600 flex items-center justify-center text-white text-lg transition-colors"
              >
                ✕
              </button>
            </div>
          </div>

          <!-- Full Model -->
          <div class="flex-1 relative">
            <model-viewer
              ref="viewerEl"
              :src="activeItem.model_url"
              :alt="activeItem.name"
              camera-controls
              shadow-intensity="1"
              environment-image="neutral"
              exposure="0.8"
              min-camera-orbit="-80deg auto auto"
              max-camera-orbit="80deg auto auto"
              style="width: 100%; height: 100%;"
            ></model-viewer>

            <!-- Zoom Controls (toggle) -->
            <Transition name="fade">
              <div v-if="showControls" class="absolute right-4 top-1/2 -translate-y-1/2 flex flex-col gap-3 z-10">
                <button
                  @click="zoomIn"
                  class="w-14 h-14 rounded-full bg-indigo-600/90 hover:bg-indigo-500 text-white text-3xl font-bold flex items-center justify-center shadow-lg transition-colors active:scale-95"
                >
                  +
                </button>
                <button
                  @click="resetZoom"
                  class="w-14 h-14 rounded-full bg-slate-600/90 hover:bg-slate-500 text-white text-lg font-bold flex items-center justify-center shadow-lg transition-colors active:scale-95"
                >
                  ↺
                </button>
                <button
                  @click="zoomOut"
                  class="w-14 h-14 rounded-full bg-indigo-600/90 hover:bg-indigo-500 text-white text-3xl font-bold flex items-center justify-center shadow-lg transition-colors active:scale-95"
                >
                  −
                </button>
              </div>
            </Transition>

            <!-- Hint -->
            <div class="absolute bottom-3 left-3 text-xs text-slate-400 bg-slate-900/60 px-2 py-1 rounded">
              {{ p.hint }}
            </div>
          </div>

          <!-- Story Bar -->
          <div class="px-4 py-3 bg-slate-900/90 backdrop-blur-sm border-t border-slate-700">
            <h4 class="text-sm font-semibold text-indigo-400 mb-1">{{ p.storyLabel }}</h4>
            <p class="text-slate-300 text-sm leading-relaxed">{{ activeItem.story }}</p>
          </div>
        </div>
      </Transition>
    </Teleport>
  </div>
</template>

<script setup>
import '@google/model-viewer'
import { ref, computed } from 'vue'
import { useSiteData } from '../composables/useSiteData.js'

const { items, page } = useSiteData()
const p = computed(() => page('wall'))

const activeItem = ref(null)
const showControls = ref(false)
const viewerEl = ref(null)

function openViewer(item) {
  activeItem.value = item
  showControls.value = false
  document.body.style.overflow = 'hidden'
}

function closeViewer() {
  activeItem.value = null
  document.body.style.overflow = ''
}

function zoomIn() {
  if (viewerEl.value) {
    const fov = parseFloat(viewerEl.value.getFieldOfView())
    viewerEl.value.fieldOfView = Math.max(fov - 10, 10) + 'deg'
  }
}
function zoomOut() {
  if (viewerEl.value) {
    const fov = parseFloat(viewerEl.value.getFieldOfView())
    viewerEl.value.fieldOfView = Math.min(fov + 10, 90) + 'deg'
  }
}
function resetZoom() {
  if (viewerEl.value) {
    viewerEl.value.fieldOfView = '45deg'
    viewerEl.value.cameraOrbit = '0deg 75deg 105%'
    viewerEl.value.minCameraOrbit = '-80deg auto auto'
    viewerEl.value.maxCameraOrbit = '80deg auto auto'
  }
}
</script>

<style scoped>
.modal-enter-active,
.modal-leave-active {
  transition: opacity 0.3s ease;
}
.modal-enter-from,
.modal-leave-to {
  opacity: 0;
}
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.25s ease;
}
.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>

// src/pages/ObjectWall.jsx
import { useState } from 'react';
import { mockItems } from '../data/mockItems';
import ModelViewer from '../components/ModelViewer';

export default function ObjectWall() {
  const [selectedItem, setSelectedItem] = useState(null);

  return (
    <div className="flex-1 flex flex-col p-6 max-w-7xl mx-auto w-full">
      <div className="mb-8">
        <h2 className="text-3xl font-extrabold text-gray-900 tracking-tight">萬物物件牆 (Object Wall)</h2>
        <p className="mt-2 text-gray-500">點擊物件以進行 360 度預覽，或使用手機開啟 AR 預覽將模型投放至現實中。</p>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
        {mockItems.map((item) => (
          <div 
            key={item.id} 
            className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden hover:shadow-xl transition-all duration-300 cursor-pointer group flex flex-col"
            onClick={() => setSelectedItem(item)}
          >
            <div className="w-full aspect-square bg-gray-50 relative overflow-hidden flex items-center justify-center">
              {/* Thumbnail placeholder or miniature viewer could go here, but an image is better for list. We'll simulate with CSS */}
              <div className="absolute inset-0 bg-gradient-to-br from-indigo-50 to-purple-50 opacity-50"></div>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1} stroke="currentColor" className="w-16 h-16 text-indigo-200 group-hover:scale-110 transition-transform duration-500">
                <path strokeLinecap="round" strokeLinejoin="round" d="M21 7.5l-9-5.25L3 7.5m18 0l-9 5.25m9-5.25v9l-9 5.25M3 7.5l9 5.25M3 7.5v9l9 5.25m0-9v9" />
              </svg>
            </div>
            <div className="p-5 flex-1 flex flex-col">
              <h3 className="text-lg font-bold text-gray-900 mb-2">{item.name}</h3>
              <p className="text-sm text-gray-500 line-clamp-2 mb-4 flex-1">{item.story}</p>
              <div className="text-indigo-600 text-sm font-medium flex items-center opacity-0 group-hover:opacity-100 transition-opacity">
                <span>點擊查看 3D</span>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="w-4 h-4 ml-1">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3" />
                </svg>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Modal for Model Viewer */}
      {selectedItem && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 sm:p-6">
          {/* Backdrop */}
          <div 
            className="absolute inset-0 bg-gray-900/60 backdrop-blur-sm transition-opacity"
            onClick={() => setSelectedItem(null)}
          ></div>
          
          {/* Modal Content */}
          <div className="relative bg-white rounded-3xl shadow-2xl w-full max-w-4xl max-h-[90vh] flex flex-col overflow-hidden animate-in fade-in zoom-in-95 duration-200">
            <button 
              onClick={() => setSelectedItem(null)}
              className="absolute top-4 right-4 z-10 p-2 bg-white/80 backdrop-blur hover:bg-gray-100 rounded-full text-gray-500 transition-colors"
            >
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="w-6 h-6">
                <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
            
            <div className="flex flex-col md:flex-row h-full">
              {/* 3D Viewer Area */}
              <div className="w-full md:w-3/5 h-[50vh] md:h-[70vh] bg-gray-50 relative">
                <ModelViewer src={selectedItem.model_url} alt={selectedItem.name} />
              </div>
              
              {/* Info Area */}
              <div className="w-full md:w-2/5 p-8 flex flex-col bg-white overflow-y-auto">
                <h3 className="text-2xl font-bold text-gray-900 mb-4">{selectedItem.name}</h3>
                <div className="w-12 h-1 bg-indigo-500 mb-6 rounded-full"></div>
                <p className="text-gray-600 leading-relaxed text-lg flex-1">
                  {selectedItem.story}
                </p>
                <div className="mt-8 pt-6 border-t border-gray-100 flex items-start gap-4 text-sm text-gray-500">
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6 text-indigo-400 shrink-0">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M12 18v-5.25m0 0a6.01 6.01 0 001.5-.189m-1.5.189a6.01 6.01 0 01-1.5-.189m3.75 7.478a12.06 12.06 0 01-4.5 0m3.75 2.383a14.406 14.406 0 01-3 0M14.25 18v-.192c0-.983.658-1.82 1.508-2.316a7.5 7.5 0 10-7.517 0c.85.496 1.509 1.333 1.509 2.316V18" />
                  </svg>
                  <p>提示：在行動裝置上點擊右下角的「AR 預覽」即可開啟擴增實境模式，將該物件放置於您的實體空間中體驗。</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
